In [1]:
import pandas as pd

In [2]:
'https://www.pgatour.com/stats/stat.101.y2022.html'

'https://www.pgatour.com/stats/stat.101.y2022.html'

In [3]:
pd.read_html('https://www.pgatour.com/stats/stat.101.y2022.html')[1]

,RANK THIS WEEK,RANK LAST WEEK,PLAYER NAME,ROUNDS,AVG.,TOTAL DISTANCE,TOTAL DRIVES
0,1,1,Cameron Champ,56,321.4,35996,112
1,2,2,Rory McIlroy,60,321.3,38561,120
2,3,3,Cameron Young,85,319.3,52373,164
3,4,4,Wyndham Clark,101,319.0,59335,186
4,5,5,Jon Rahm,74,318.9,44646,140
...,...,...,...,...,...,...,...
188,189,189,Vaughn Taylor,57,284.7,30175,106
189,190,190,Joshua Creel,53,284.6,26750,94
190,191,191,Chez Reavie,91,283.9,48269,170
191,192,192,Brendon Todd,87,279.0,44079,158
192,193,193,Brian Stuard,95,277.4,49383,178

In [4]:
df = pd.read_html('https://www.pgatour.com/stats/stat.101.y2022.html')[1]

In [5]:
df.head(4)

,RANK THIS WEEK,RANK LAST WEEK,PLAYER NAME,ROUNDS,AVG.,TOTAL DISTANCE,TOTAL DRIVES
0,1,1,Cameron Champ,56,321.4,35996,112
1,2,2,Rory McIlroy,60,321.3,38561,120
2,3,3,Cameron Young,85,319.3,52373,164
3,4,4,Wyndham Clark,101,319.0,59335,186

In [6]:
df.columns

Index(['RANK THIS WEEK', 'RANK LAST WEEK', 'PLAYER NAME', 'ROUNDS', 'AVG.',
       'TOTAL DISTANCE', 'TOTAL DRIVES'],
      dtype='object')

In [7]:
df1 = df.drop(['RANK\u00a0THIS WEEK','RANK LAST WEEK','ROUNDS','TOTAL DISTANCE','TOTAL DRIVES'],axis=1)

In [9]:
len(df1)

193

In [10]:
df1.head(12)

        PLAYER NAME   AVG.
0     Cameron Champ  321.4
1      Rory McIlroy  321.3
2     Cameron Young  319.3
3     Wyndham Clark  319.0
4          Jon Rahm  318.9
5     Matthew Wolff  318.4
6   Joseph Bramlett  318.3
7      Brandon Hagy  317.9
8     Trey Mullinax  317.2
9   Taylor Pendrith  316.1
10  Jhonattan Vegas  315.7
11        Luke List  314.8

In [11]:
df2 = df1[df1['AVG.'] > 315]

In [12]:
df2.rename(columns={'PLAYER NAME': 'Player Name', 'AVG.': 'Average'}, inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5047: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [13]:
df2.head(14)

        Player Name  Average
0     Cameron Champ    321.4
1      Rory McIlroy    321.3
2     Cameron Young    319.3
3     Wyndham Clark    319.0
4          Jon Rahm    318.9
5     Matthew Wolff    318.4
6   Joseph Bramlett    318.3
7      Brandon Hagy    317.9
8     Trey Mullinax    317.2
9   Taylor Pendrith    316.1
10  Jhonattan Vegas    315.7

In [ ]:
exported_values = list( df2.T.to_dict().values() )

In [ ]:
import json

In [ ]:

# json.dumps(exported_values)

In [ ]:
open('PGADrivingStats.json','w').write(json.dumps(exported_values))

NameError: ignored