In [ ]:
pip install googlemaps

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting googlemaps
  Downloading googlemaps-4.7.3.tar.gz (32 kB)
Requirement already satisfied: requests<3.0,>=2.20.0 in /usr/local/lib/python3.8/dist-packages (from googlemaps) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2022.12.7)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py) ... done
  Created wheel for googlemaps: filename=googlemaps-4.7.3-py3-none-any.whl size=40341 sha256=62e1319beb0f93c4714d5c87ec70df233112c84404c271e82b77f215b608fa12
  Stored in directory: /root/.cache/pip/wheels/e0/57/cc/329195e1c9e5b7d270fba4671c451d111d08f7b7ef56f8ec30
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.7.3

In [ ]:
import googlemaps
import pandas as pd
import re 
import numpy as np

In [ ]:
KEY = "AIzaSyDQf5cNhZKbNvGt73rDBYYWN87bna7z0Ek"

In [ ]:
gmaps =  googlemaps.Client(key=KEY)

In [ ]:
# load dataset
df = pd.read_csv("rmclean_29-12.csv")

In [ ]:
#Using the google API to get coordinates
def get_coordinates(address):
    geocode_result = gmaps.geocode(str(address))
    if len(geocode_result) > 0:
        return list(geocode_result[0]['geometry']['location'].values())
    else:
        return [np.NaN, np.NaN]

In [ ]:

coordinates2 = df['Address'].apply(lambda x: pd.Series(get_coordinates(x), index=['Latitude', 'Longitude']))

In [ ]:
coordinates2.head(3)

    Latitude  Longitude
0  51.517496  -0.100046
1  51.511134  -0.077605
2  51.520525  -0.096939

In [ ]:
#bring data frames together
df = pd.concat([df[:], coordinates2[:]], axis="columns")

In [ ]:
df.head(4)

,Unnamed: 0,Address,Description,Price,Postcode,Full_Postcode,number_bedrooms,Latitude,Longitude
0,0,"Barts Square, 56 West Smithfield, Smithfield M...",2 bedroom apartment for sale,1660000.0,EC1A,NaN,2.0,51.517496,-0.100046
1,1,"26 Savage Gardens, London, EC3N 2AR",1 bedroom flat for sale,550000.0,EC3N,EC3N 2AR,1.0,51.511134,-0.077605
2,2,"Barbican, John Trundle Court",Studio flat for sale,450000.0,NaN,NaN,0.0,51.520525,-0.096939
3,3,"Little Britain, Little Britain",2 bedroom flat for sale,699950.0,NaN,NaN,2.0,NaN,NaN

In [ ]:
df.to_csv("rmgeolocation_29-12.csv")